# Site settings
title: aboutDevs
header-img: img/home.png
email: santosjr87@gmail.com
description: "Compartilhando conhecimento e experiencias."
baseurl: "/aboutdevs-clean"
url: "http://aboutdevs.com"
twitter_username: anchiietajr
github_username:  anchietajunior

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
